logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      package-to-scan: com.javanautas.fakeapius.infrastructure.entities
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true
      
fake-api:
  url: https://fakestoreapi.com

server:
  port: 8181